reviewers:
  defaults:
    - editors
  groups:
    editors:
      - jcstein
      - ebuchman
      - rootulp
      - cmwaters
files:
"**":
  - editors
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 4
